[env]
SYN_HORSE_MISE_ACTIVE = 'true'
V0_API_KEY = ''
NUXT_OG_IMAGE_SECRET = 'slartibartfast'
TMPDIR = '/tmp'

[settings]
env_file = '.env'

[tools]
node = { version = '24.20.0' }

[tasks]
claude = 'npx --yes @anthropic-ai/claude-code@latest'
