name: ci
permissions: read-all
on:
  push: null
  pull_request: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: trunk
        uses: trunk-io/trunk-action@bf81325059d2534b31df5365182237788c5e0338
      - name: node
        uses: actions/setup-node@54045abd5dcd3b0fee9ca02fa24c57545834c9cc
        with:
          node-version-file: .node-version
      - name: bun
        uses: oven-sh/setup-bun@4c32875876eebbbb9bc34b8ee07ba2d7bb4b3462
        with:
          bun-version-file: .bun-version
      - name: install-pass1
        run: bun install
      - name: install-trust
        run: bun pm trust --all
      - name: install-pass2
        run: bun install
      - name: typecheck
        run: bun run lint:types
      - name: build
        run: bun run build
