name: ci
permissions: read-all
on:
  push: null
  pull_request: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: node
        uses: actions/setup-node@efcb663fc60e97218a2b2d6d827f7830f164739e
        with:
          node-version-file: .node-version
      - name: bun
        uses: oven-sh/setup-bun@ab8cb4e8f89912a29b87e4abc4554f2301648a5c
        with:
          bun-version-file: .bun-version
      - name: install-pass1
        run: bun install
      - name: install-trust
        run: bun pm trust --all
      - name: install-pass2
        run: bun install
      - name: trunk
        uses: trunk-io/trunk-action@bf81325059d2534b31df5365182237788c5e0338
      - name: typecheck
        run: bun run lint:types
      - name: build
        run: bun run build
